project:
  type: website
  output-dir: docs

website:
  title: ""
  favicon: "logos/Untitled_Artwork 26.png"
  navbar:
    logo: "logos/Untitled_Artwork 26.png"
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: tsinghua.qmd
        text: Highlights
      - href: artwork.qmd
        text: Artwork

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: false
    page-layout: full



